name 'hadoop'
maintainer 'Jonathan Card'
maintainer_email 'jcard@buildanemdrive.org'
license 'all_rights'
description 'Installs/Configures hadoop'
long_description 'Installs/Configures hadoop'
version '0.1.0'

depends 'ssh_keygen'
depends 'hostname'